#ifndef GAME_STATE_H
#define GAME_STATE_H

enum {
    OVERLAY_NONE = 0,
    OVERLAY_WATER = 2,
    OVERLAY_RELIGION = 4,
    OVERLAY_FIRE = 8,
    OVERLAY_DAMAGE = 9,
    OVERLAY_CRIME = 10,
    OVERLAY_ENTERTAINMENT = 11,
    OVERLAY_THEATER = 12,
    OVERLAY_AMPHITHEATER = 13,
    OVERLAY_COLOSSEUM = 14,
    OVERLAY_HIPPODROME = 15,
    OVERLAY_EDUCATION = 16,
    OVERLAY_SCHOOL = 17,
    OVERLAY_LIBRARY = 18,
    OVERLAY_ACADEMY = 19,
    OVERLAY_BARBER = 20,
    OVERLAY_BATHHOUSE = 21,
    OVERLAY_CLINIC = 22,
    OVERLAY_HOSPITAL = 23,
    OVERLAY_TAX_INCOME = 24,
    OVERLAY_FOOD_STOCKS = 25,
    OVERLAY_DESIRABILITY = 26,
    OVERLAY_WORKERS_UNUSED = 27,
    OVERLAY_NATIVE = 28,
    OVERLAY_PROBLEMS = 29,
    OVERLAY_ROADS = 30,
    OVERLAY_LEVY = 31,
    OVERLAY_TAVERN = 32,
    OVERLAY_ARENA = 33,
    OVERLAY_SENTIMENT = 34,
    OVERLAY_MOTHBALL = 35,
    OVERLAY_ENEMY = 36,
    OVERLAY_LOGISTICS = 37,
    OVERLAY_SICKNESS = 38,
    OVERLAY_EFFICIENCY = 39,
    OVERLAY_STORAGES = 40,
    OVERLAY_HEALTH = 41,
    OVERLAY_EMPLOYMENT = 42,
    OVERLAY_HOUSING = 43,
    OVERLAY_HOUSE_SMALL_TENT = 44,
    OVERLAY_HOUSE_LARGE_TENT = 45,
    OVERLAY_HOUSE_SMALL_SHACK = 46,
    OVERLAY_HOUSE_LARGE_SHACK = 47,
    OVERLAY_HOUSE_SMALL_HOVEL = 48,
    OVERLAY_HOUSE_LARGE_HOVEL = 49,
    OVERLAY_HOUSE_SMALL_CASA = 50,
    OVERLAY_HOUSE_LARGE_CASA = 51,
    OVERLAY_HOUSE_SMALL_INSULA = 52,
    OVERLAY_HOUSE_MEDIUM_INSULA = 53,
    OVERLAY_HOUSE_LARGE_INSULA = 54,
    OVERLAY_HOUSE_GRAND_INSULA = 55,
    OVERLAY_HOUSE_SMALL_VILLA = 56,
    OVERLAY_HOUSE_MEDIUM_VILLA = 57,
    OVERLAY_HOUSE_LARGE_VILLA = 58,
    OVERLAY_HOUSE_GRAND_VILLA = 59,
    OVERLAY_HOUSE_SMALL_PALACE = 60,
    OVERLAY_HOUSE_MEDIUM_PALACE = 61,
    OVERLAY_HOUSE_LARGE_PALACE = 62,
    OVERLAY_HOUSE_LUXURY_PALACE = 63,
    OVERLAY_HOUSING_GROUPS_TENTS = 64,
    OVERLAY_HOUSING_GROUPS = 65,
    OVERLAY_HOUSING_GROUPS_SHACKS = 66,
    OVERLAY_HOUSING_GROUPS_HOVELS = 67,
    OVERLAY_HOUSING_GROUPS_CASAE = 68,
    OVERLAY_HOUSING_GROUPS_INSULAE = 69,
    OVERLAY_HOUSING_GROUPS_VILLAS = 70,
    OVERLAY_HOUSING_GROUPS_PALACES = 71
};

void game_state_init(void);

int game_state_is_paused(void);

void game_state_toggle_paused(void);

void game_state_pause(void);

void game_state_unpause(void);

int game_state_overlay(void);

void game_state_reset_overlay(void);

void game_state_toggle_overlay(void);

void game_state_set_overlay(int overlay);

#endif // GAME_STATE_H
