#ifndef EMPIRE_BUILDING_TYPE_H
#define EMPIRE_BUILDING_TYPE_H

typedef enum {
    EMPIRE_BUILDING_NONE = 0,
    EMPIRE_BUILDING_WHARF = 1,
    EMPIRE_BUILDING_WOODCUTTER = 2,
    EMPIRE_BUILDING_WALLS = 3,
    EMPIRE_BUILDING_HIGHWAY = 4,
    EMPIRE_BUILDING_TYPE_MAX = 5,
} empire_building_type;

#endif // EMPIRE_BUILDING_TYPE_H
